import { Playlist } from "./Model/Playlist/playlist";

export const playlists: Playlist[] = [
  {
    name: "Liked Songs",
    image: "img",
    songs: ['1'],
    createdBy: "Poloaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    isPinned: true,
  },
  {
    name: "Pinned 1",
    image: "img",
    songs: ['1'],
    createdBy: "someone",
    isPinned: true,
  },
  {
    name: "Pinned 2",
    image: "img",
    songs: ['1'],
    createdBy: "Me",
    isPinned: true,
  },
  {
    name: "PLaylist 1",
    image: "img",
    songs: ['1'],
    createdBy: "Me",
    isPinned: false,
  },
  {
    name: "PLaylist 2",
    image: "img",
    songs: ['1'],
    createdBy: "someone",
    isPinned: false,
  },
  {
    name: "PLaylist 2",
    image: "img",
    songs: ['1'],
    createdBy: "someone",
    isPinned: false,
  },
  {
    name: "PLaylist 2",
    image: "img",
    songs: ['1'],
    createdBy: "someone",
    isPinned: false,
  },
  {
    name: "PLaylist 2",
    image: "img",
    songs: ['1'],
    createdBy: "someone",
    isPinned: false,
  },
  {
    name: "PLaylist 2",
    image: "img",
    songs: ['1'],
    createdBy: "someone",
    isPinned: false,
  },
  {
    name: "PLaylist 2",
    image: "img",
    songs: ['1'],
    createdBy: "someone",
    isPinned: false,
  },
  {
    name: "PLaylist 2",
    image: "img",
    songs: ['1'],
    createdBy: "someone",
    isPinned: false,
  },
  {
    name: "PLaylist 2",
    image: "img",
    songs: ['1'],
    createdBy: "someone",
    isPinned: false,
  },
];
