import { Playlist } from "./Model/Playlist/playlist";

export const playlists: Playlist[] = [
  {
    name: "Liked Songs",
    image: "",
    songs: ["1"],
    createdBy: "Poloaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    isPinned: true,
  },
  {
    name: "The Duck Songs",
    image: "/Images/theDuckSongCover.png",
    songs: ["5"],
    createdBy: "forrestfire101",
    isPinned: true,
  },
  {
    name: "Pinned 2",
    image: "",
    songs: ["1"],
    createdBy: "Me",
    isPinned: true,
  },
  {
    name: "PLaylist 1",
    image: "",
    songs: ["1"],
    createdBy: "Me, me, me, me, me, me, me, me, you",
    isPinned: false,
  },
  {
    name: "PLaylist 2",
    image: "",
    songs: ["1"],
    createdBy: "someone",
    isPinned: false,
  },
  {
    name: "PLaylist 2",
    image: "",
    songs: ["1"],
    createdBy: "someone",
    isPinned: false,
  },
  {
    name: "PLaylist 2",
    image: "",
    songs: ["1"],
    createdBy: "someone",
    isPinned: false,
  },
  {
    name: "PLaylist 2",
    image: "",
    songs: ["1"],
    createdBy: "someone",
    isPinned: false,
  },
  {
    name: "PLaylist 2",
    image: "",
    songs: ["1"],
    createdBy: "someone",
    isPinned: false,
  },
  {
    name: "PLaylist 2",
    image: "",
    songs: ["1"],
    createdBy: "someone",
    isPinned: false,
  },
  {
    name: "PLaylist 2",
    image: "",
    songs: ["1"],
    createdBy: "someone",
    isPinned: false,
  },
  {
    name: "PLaylist 2",
    image: "",
    songs: ["1"],
    createdBy: "someone",
    isPinned: false,
  },
];
